const asmaulHusna = [
  {
    id: 1,
    arab: "الرَّحْمَٰنُ",
    latin: "Ar-Rahman",
    indonesia: "Yang Maha Pengasih",
  },
  {
    id: 2,
    arab: "الرَّحِيمُ",
    latin: "Ar-Rahim",
    indonesia: "Yang Maha Penyayang",
  },
  {
    id: 3,
    arab: "الْمَلِكُ",
    latin: "Al-Malik",
    indonesia: "Yang Maha Merajai",
  },
  {
    id: 4,
    arab: "الْقُدُّوسُ",
    latin: "Al-Quddus",
    indonesia: "Yang Maha Suci",
  },
  {
    id: 5,
    arab: "السَّلاَمُ",
    latin: "As-Salam",
    indonesia: "Yang Maha Memberi Kesejahteraan",
  },
  {
    id: 6,
    arab: "الْمُؤْمِنُ",
    latin: "Al-Mu'min",
    indonesia: "Yang Maha Memberi Keamanan",
  },
  {
    id: 7,
    arab: "الْمُهَيْمِنُ",
    latin: "Al-Muhaimin",
    indonesia: "Yang Maha Mengawasi",
  },
  {
    id: 8,
    arab: "الْعَزِيزُ",
    latin: "Al-Aziz",
    indonesia: "Yang Maha Perkasa",
  },
  {
    id: 9,
    arab: "الْجَبَّارُ",
    latin: "Al-Jabbar",
    indonesia: "Yang Maha Perkasa",
  },
  {
    id: 10,
    arab: "الْمُتَكَبِّرُ",
    latin: "Al-Mutakabbir",
    indonesia: "Yang Maha Megah",
  },
  {
    id: 11,
    arab: "الْخَالِقُ",
    latin: "Al-Khaliq",
    indonesia: "Yang Maha Pencipta",
  },
  {
    id: 12,
    arab: "الْبَارِئُ",
    latin: "Al-Bari'",
    indonesia: "Yang Maha Melepaskan",
  },
  {
    id: 13,
    arab: "الْمُصَوِّرُ",
    latin: "Al-Musawwir",
    indonesia: "Yang Maha Membentuk",
  },
  {
    id: 14,
    arab: "الْغَفَّارُ",
    latin: "Al-Ghaffar",
    indonesia: "Yang Maha Pengampun",
  },
  {
    id: 15,
    arab: "الْقَهَّارُ",
    latin: "Al-Qahhar",
    indonesia: "Yang Maha Menundukkan",
  },
  {
    id: 16,
    arab: "الْوَهَّابُ",
    latin: "Al-Wahhab",
    indonesia: "Yang Maha Pemberi Karunia",
  },
  {
    id: 17,
    arab: "الرَّزَّاقُ",
    latin: "Ar-Razzaq",
    indonesia: "Yang Maha Pemberi Rezeki",
  },
  {
    id: 18,
    arab: "الْفَتَّاحُ",
    latin: "Al-Fattah",
    indonesia: "Yang Maha Pembuka",
  },
  {
    id: 19,
    arab: "الْعَلِيمُ",
    latin: "Al-‘Alim",
    indonesia: "Yang Maha Mengetahui",
  },
  {
    id: 20,
    arab: "الْقَابِضُ",
    latin: "Al-Qabidh",
    indonesia: "Yang Maha Menyempitkan",
  },
  {
    id: 21,
    arab: "الْبَاسِطُ",
    latin: "Al-Basit",
    indonesia: "Yang Maha Melapangkan",
  },
  {
    id: 22,
    arab: "الْخَافِضُ",
    latin: "Al-Khafidh",
    indonesia: "Yang Maha Merendahkan",
  },
  {
    id: 23,
    arab: "الرَّافِعُ",
    latin: "Ar-Rafi‘",
    indonesia: "Yang Maha Meninggikan",
  },
  {
    id: 24,
    arab: "الْمُعِزُّ",
    latin: "Al-Mu‘izz",
    indonesia: "Yang Maha Memuliakan",
  },
  {
    id: 25,
    arab: "الْمُذِلُّ",
    latin: "Al-Mudhill",
    indonesia: "Yang Maha Menghinakan",
  },
  {
    id: 26,
    arab: "السَّمِيعُ",
    latin: "As-Sami‘",
    indonesia: "Yang Maha Mendengar",
  },
  {
    id: 27,
    arab: "الْبَصِيرُ",
    latin: "Al-Basir",
    indonesia: "Yang Maha Melihat",
  },
  {
    id: 28,
    arab: "الْحَكَمُ",
    latin: "Al-Hakam",
    indonesia: "Yang Maha Menetapkan",
  },
  {
    id: 29,
    arab: "الْعَدْلُ",
    latin: "Al-‘Adl",
    indonesia: "Yang Maha Adil",
  },
  {
    id: 30,
    arab: "اللَّطِيفُ",
    latin: "Al-Latif",
    indonesia: "Yang Maha Lembut",
  },
  {
    id: 31,
    arab: "الْخَبِيرُ",
    latin: "Al-Khabir",
    indonesia: "Yang Maha Mengetahui",
  },
  {
    id: 32,
    arab: "الْحَلِيمُ",
    latin: "Al-Halim",
    indonesia: "Yang Maha Penyantun",
  },
  {
    id: 33,
    arab: "الْعَظِيمُ",
    latin: "Al-‘Azim",
    indonesia: "Yang Maha Agung",
  },
  {
    id: 34,
    arab: "الْغَفُورُ",
    latin: "Al-Ghafur",
    indonesia: "Yang Maha Pengampun",
  },
  {
    id: 35,
    arab: "الشَّكُورُ",
    latin: "Ash-Shakur",
    indonesia: "Yang Maha Mensyukuri",
  },
  {
    id: 36,
    arab: "الْعَلِيُّ",
    latin: "Al-‘Aliyy",
    indonesia: "Yang Maha Tinggi",
  },
  {
    id: 37,
    arab: "الْكَبِيرُ",
    latin: "Al-Kabir",
    indonesia: "Yang Maha Besar",
  },
  {
    id: 38,
    arab: "الْحَفِيظُ",
    latin: "Al-Hafizh",
    indonesia: "Yang Maha Memelihara",
  },
  {
    id: 39,
    arab: "المُقيِتُ",
    latin: "Al-Muqit",
    indonesia: "Yang Maha Pemberi Kecukupan",
  },
  {
    id: 40,
    arab: "الْحَسِيبُ",
    latin: "Al-Hasib",
    indonesia: "Yang Maha Membuat Perhitungan",
  },
  {
    id: 41,
    arab: "الْجَلِيلُ",
    latin: "Al-Jalil",
    indonesia: "Yang Maha Mulia",
  },
  {
    id: 42,
    arab: "الْكَرِيمُ",
    latin: "Al-Karim",
    indonesia: "Yang Maha Pemurah",
  },
  {
    id: 43,
    arab: "الرَّقِيبُ",
    latin: "Ar-Raqib",
    indonesia: "Yang Maha Mengawasi",
  },
  {
    id: 44,
    arab: "الْمُجِيبُ",
    latin: "Al-Mujib",
    indonesia: "Yang Maha Mengabulkan",
  },
  {
    id: 45,
    arab: "الْوَاسِعُ",
    latin: "Al-Wasi‘",
    indonesia: "Yang Maha Luas",
  },
  {
    id: 46,
    arab: "الْحَكِيمُ",
    latin: "Al-Hakim",
    indonesia: "Yang Maha Bijaksana",
  },
  {
    id: 47,
    arab: "الْوَدُودُ",
    latin: "Al-Wadud",
    indonesia: "Yang Maha Mengasihi",
  },
  {
    id: 48,
    arab: "الْمَجِيدُ",
    latin: "Al-Majid",
    indonesia: "Yang Maha Mulia",
  },
  {
    id: 49,
    arab: "الْبَاعِثُ",
    latin: "Al-Ba‘ith",
    indonesia: "Yang Maha Menghidupkan",
  },
  {
    id: 50,
    arab: "الشَّهِيدُ",
    latin: "Ash-Shahid",
    indonesia: "Yang Maha Menyaksikan",
  },
  {
    id: 51,
    arab: "الْحَقُّ",
    latin: "Al-Haqq",
    indonesia: "Yang Maha Benar",
  },
  {
    id: 52,
    arab: "الْوَكِيلُ",
    latin: "Al-Wakil",
    indonesia: "Yang Maha Memelihara",
  },
  {
    id: 53,
    arab: "الْقَوِيُّ",
    latin: "Al-Qawiyy",
    indonesia: "Yang Maha Kuat",
  },
  {
    id: 54,
    arab: "الْمَتِينُ",
    latin: "Al-Matin",
    indonesia: "Yang Maha Kokoh",
  },
  {
    id: 55,
    arab: "الْوَلِيُّ",
    latin: "Al-Waliyy",
    indonesia: "Yang Maha Melindungi",
  },
  {
    id: 56,
    arab: "الْحَمِيدُ",
    latin: "Al-Hamid",
    indonesia: "Yang Maha Terpuji",
  },
  {
    id: 57,
    arab: "الْمُحْصِي",
    latin: "Al-Muhsi",
    indonesia: "Yang Maha Menghitung",
  },
  {
    id: 58,
    arab: "الْمُبْدِئُ",
    latin: "Al-Mubdi‘",
    indonesia: "Yang Maha Memulai",
  },
  {
    id: 59,
    arab: "الْمُعِيدُ",
    latin: "Al-Mu‘id",
    indonesia: "Yang Maha Mengembalikan",
  },
  {
    id: 60,
    arab: "الْمُحْيِي",
    latin: "Al-Muhyi",
    indonesia: "Yang Maha Menghidupkan",
  },
  {
    id: 61,
    arab: "الْمُمِيتُ",
    latin: "Al-Mumit",
    indonesia: "Yang Maha Mematikan",
  },
  {
    id: 62,
    arab: "الْحَيُّ",
    latin: "Al-Hayy",
    indonesia: "Yang Maha Hidup",
  },
  {
    id: 63,
    arab: "الْقَيُّومُ",
    latin: "Al-Qayyum",
    indonesia: "Yang Maha Mandiri",
  },
  {
    id: 64,
    arab: "الْوَاجِدُ",
    latin: "Al-Wajid",
    indonesia: "Yang Maha Menemukan",
  },
  {
    id: 65,
    arab: "الْمَاجِدُ",
    latin: "Al-Majid",
    indonesia: "Yang Maha Mulia",
  },
  {
    id: 66,
    arab: "الْوَاحِدُ",
    latin: "Al-Wahid",
    indonesia: "Yang Maha Esa",
  },
  {
    id: 67,
    arab: "الْأَحَدُ",
    latin: "Al-Ahad",
    indonesia: "Yang Maha Tunggal",
  },
  {
    id: 68,
    arab: "الصَّمَدُ",
    latin: "As-Samad",
    indonesia: "Yang Maha Dibutuhkan, Tempat Meminta",
  },
  {
    id: 69,
    arab: "الْقَادِرُ",
    latin: "Al-Qadir",
    indonesia: "Yang Maha Menentukan, Maha Kuasa",
  },
  {
    id: 70,
    arab: "الْمُقْتَدِرُ",
    latin: "Al-Muqtadir",
    indonesia: "Yang Maha Berkuasa",
  },
  {
    id: 71,
    arab: "الْمُقَدِّمُ",
    latin: "Al-Muqaddim",
    indonesia: "Yang Maha Mendahulukan",
  },
  {
    id: 72,
    arab: "الْمُؤَخِّرُ",
    latin: "Al-Mu'akhkhir",
    indonesia: "Yang Maha Mengakhirkan",
  },
  {
    id: 73,
    arab: "الْأَوَّلُ",
    latin: "Al-Awwal",
    indonesia: "Yang Maha Awal",
  },
  {
    id: 74,
    arab: "الْآخِرُ",
    latin: "Al-Akhir",
    indonesia: "Yang Maha Akhir",
  },
  {
    id: 75,
    arab: "الظَّاهِرُ",
    latin: "Az-Zahir",
    indonesia: "Yang Maha Nyata",
  },
  {
    id: 76,
    arab: "الْبَاطِنُ",
    latin: "Al-Batin",
    indonesia: "Yang Maha Ghaib",
  },
  {
    id: 77,
    arab: "الْوَالِي",
    latin: "Al-Wali",
    indonesia: "Yang Maha Memerintah",
  },
  {
    id: 78,
    arab: "الْمُتَعَالِي",
    latin: "Al-Muta'ali",
    indonesia: "Yang Maha Tinggi",
  },
  {
    id: 79,
    arab: "الْبَرُّ",
    latin: "Al-Barr",
    indonesia: "Yang Maha Penderma",
  },
  {
    id: 80,
    arab: "التَّوَّابُ",
    latin: "At-Tawwab",
    indonesia: "Yang Maha Penerima Tobat",
  },
  {
    id: 81,
    arab: "الْمُنْتَقِمُ",
    latin: "Al-Muntaqim",
    indonesia: "Yang Maha Pemberi Balasan",
  },
  {
    id: 82,
    arab: "العَفُوُّ",
    latin: "Al-Afuww",
    indonesia: "Yang Maha Pemaaf",
  },
  {
    id: 83,
    arab: "الرَّؤُوفُ",
    latin: "Ar-Ra'uf",
    indonesia: "Yang Maha Pengasuh",
  },
  {
    id: 84,
    arab: "مَالِكُ الْمُلْكِ",
    latin: "Malikul Mulk",
    indonesia: "Yang Maha Penguasa Kerajaan",
  },
  {
    id: 85,
    arab: "ذُو الْجَلَالِ وَالْإِكْرَامِ",
    latin: "Dzul-Jalali wal-Ikram",
    indonesia: "Yang Maha Pemilik Kebesaran dan Kemuliaan",
  },
  {
    id: 86,
    arab: "الْمُقْسِطُ",
    latin: "Al-Muqsit",
    indonesia: "Yang Maha Pemberi Keadilan",
  },
  {
    id: 87,
    arab: "الْجَامِعُ",
    latin: "Al-Jami‘",
    indonesia: "Yang Maha Mengumpulkan",
  },
  {
    id: 88,
    arab: "الْغَنِيُّ",
    latin: "Al-Ghaniyy",
    indonesia: "Yang Maha Kaya",
  },
  {
    id: 89,
    arab: "الْمُغْنِي",
    latin: "Al-Mughni",
    indonesia: "Yang Maha Memberi Kekayaan",
  },
  {
    id: 90,
    arab: "الْمَانِعُ",
    latin: "Al-Mani‘",
    indonesia: "Yang Maha Mencegah",
  },
  {
    id: 91,
    arab: "الضَّارُّ",
    latin: "Ad-Darr",
    indonesia: "Yang Maha Penimpa Kemudaratan",
  },
  {
    id: 92,
    arab: "النَّافِعُ",
    latin: "An-Nafi‘",
    indonesia: "Yang Maha Memberi Manfaat",
  },
  {
    id: 93,
    arab: "النُّورُ",
    latin: "An-Nur",
    indonesia: "Yang Maha Bercahaya",
  },
  {
    id: 94,
    arab: "الْهَادِي",
    latin: "Al-Hadi",
    indonesia: "Yang Maha Pemberi Petunjuk",
  },
  {
    id: 95,
    arab: "البديع",
    latin: "Al Badii’",
    indonesia: "Yang Maha Pencipta",
  },
  {
    id: 96,
    arab: "الباقي",
    latin: "Al Baaqii",
    indonesia: "Yang Maha Kekal",
  },
  {
    id: 97,
    arab: "الوارث",
    latin: "Al Waarits",
    indonesia: "Yang Maha Pewaris",
  },
  {
    id: 98,
    arab: "الرشيد",
    latin: "Ar Rasyiid",
    indonesia: "Yang Maha Pandai",
  },
  {
    id: 99,
    arab: "الصبور",
    latin: "As Shabuur ",
    indonesia: "Yang Maha Sabar",
  },
];

export default asmaulHusna;
